version: "3.9"

networks:
  one_lab:
    driver: bridge

volumes:
  api_data:

services:
  app:
    build: .
    ports:
      - "8081:${WEB_SERVER_PORT}"
    volumes:
      - .:/src
    env_file:
      - .env
    environment:
      - TZ=Asia/Almaty
    networks:
      - one_lab
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres:13.2-alpine
    volumes:
      - api_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${PGSQL_USER}
      - POSTGRES_PASSWORD=${PGSQL_PASSWORD}
      - POSTGRES_DB=${PGSQL_DB}
    networks:
      - one_lab
    ports:
      - "5433:${PGSQL_PORT}"
  redis:
    image: redis:alpine
    networks:
      - one_lab
    ports:
      - "6379:6379"